# Generated by Django 5.2.7 on 2025-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.CharField(max_length=100)),
                ('البريد_الإلكتروني', models.EmailField(max_length=254, unique=True)),
                ('رقم_الجوال', models.CharField(max_length=15)),
            ],
        ),
    ]
