# Generated by Django 5.2.7 on 2025-10-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('تاريخ_البدء', models.DateTimeField()),
                ('تاريخ_الانتهاء', models.DateTimeField()),
                ('تم_الدفع', models.BooleanField(default=False)),
                ('السيارة', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fleet.car')),
                ('العميل', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.client')),
            ],
        ),
    ]
